module:
  block: 0
  block_content: 0
  config: 0
  contextual: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  locale: 0
  markdown: 0
  media: 0
  media_library: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  system: 0
  text: 0
  update: 0
  user: 0
  views_ui: 0
  views: 10
  minimal: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  baxter_t: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
